// <auto-generated />
namespace Project4_EfCodeFirstMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class v1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1));
        
        string IMigrationMetadata.Id
        {
            get { return "202411101634219_v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
